/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CalHashInterface extends ethers.utils.Interface {
  functions: {
    "getInitHash()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getInitHash",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getInitHash",
    data: BytesLike
  ): Result;

  events: {};
}

export class CalHash extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CalHashInterface;

  functions: {
    getInitHash(overrides?: CallOverrides): Promise<[string]>;

    "getInitHash()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getInitHash(overrides?: CallOverrides): Promise<string>;

  "getInitHash()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getInitHash(overrides?: CallOverrides): Promise<string>;

    "getInitHash()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getInitHash(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitHash()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getInitHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getInitHash()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
