/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IGovernableInterface extends ethers.utils.Interface {
  functions: {
    "isGovernor(address)": FunctionFragment;
    "isMastermind(address)": FunctionFragment;
    "isPartner(address)": FunctionFragment;
    "isUser(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isGovernor", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isMastermind",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isPartner", values: [string]): string;
  encodeFunctionData(functionFragment: "isUser", values: [string]): string;

  decodeFunctionResult(functionFragment: "isGovernor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMastermind",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPartner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isUser", data: BytesLike): Result;

  events: {};
}

export class IGovernable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IGovernableInterface;

  functions: {
    isGovernor(_address: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isGovernor(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isMastermind(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isMastermind(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isPartner(_address: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isPartner(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isUser(_address: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isUser(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  isGovernor(_address: string, overrides?: CallOverrides): Promise<boolean>;

  "isGovernor(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isMastermind(_address: string, overrides?: CallOverrides): Promise<boolean>;

  "isMastermind(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isPartner(_address: string, overrides?: CallOverrides): Promise<boolean>;

  "isPartner(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isUser(_address: string, overrides?: CallOverrides): Promise<boolean>;

  "isUser(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    isGovernor(_address: string, overrides?: CallOverrides): Promise<boolean>;

    "isGovernor(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isMastermind(_address: string, overrides?: CallOverrides): Promise<boolean>;

    "isMastermind(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPartner(_address: string, overrides?: CallOverrides): Promise<boolean>;

    "isPartner(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isUser(_address: string, overrides?: CallOverrides): Promise<boolean>;

    "isUser(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isGovernor(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isGovernor(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMastermind(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isMastermind(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPartner(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isPartner(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isUser(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isUser(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isGovernor(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isGovernor(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMastermind(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isMastermind(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPartner(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isPartner(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isUser(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isUser(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
